template_path: "jumpcloud-idp.yaml"
stack_name: "jc-saml-testitorgmgnt-admin"
stack_tags:
  Project: "Infrastructure"
parameters:
  SamlProviderName: "testitorgmgnt-admin"
  SamlProviderPolicyArns:
    - "arn:aws:iam::aws:policy/AdministratorAccess"
    - "arn:aws:iam::aws:policy/job-function/Billing"
  MetadataDocument: !file_contents idp/jumpcloud/testitorgmgnt-admin.xml
dependencies:
  - "testitorgmgnt/cfn-cr-saml-provider.yaml"
