project_code: "sage-bionetworks"
profile: {{ var.profile | default("default") }}
region: {{ var.region | default("us-east-1") }}
template_key_prefix: {{ environment_variable.TRAVIS_BRANCH | default("testing") }}
template_bucket_name: "sceptre-cloudformation-bucket-bucket-aln2huqmexuc"
admincentral_cf_bucket: "bootstrap-awss3cloudformationbucket-19qromfd235z9"
