AWSTemplateFormatVersion: '2010-09-09-OC'
Description: org-formation template for organizations management account

Organization:
  MasterAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      AccountName: org-sagebase-testitorgmgnt
      Alias: org-sagebase-testitorgmgnt
      AccountId: '928879890086'
      RootEmail: aws.testitorgmgnt@sagebase.org
      Tags:
        <<: !Include ./_default_org_tags.yaml
        budget-alarm-threshold: '100'
        account-owner-email: aws.testitorgmgnt@sagebase.org

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:
      DefaultOrganizationAccessRoleName: OrganizationAccountAccessRole

  DevelopmentOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: development
      Accounts:
        - !Ref MemberXAccount

  ProductionOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: production
      Accounts:
        - !Ref MemberYAccount

  MemberXAccount:
    Type: OC::ORG::Account
    Properties:
      Alias: org-sagebase-testitorgmgnt-memberx
      AccountName: org-sagebase-testitorgmgnt-memberx
      RootEmail: aws.testitorgmgnt.memberx@sagebase.org
      Tags:
        <<: !Include ./_default_org_tags.yaml
        budget-alarm-threshold: '40'
        account-owner-email: aws.testitorgmgnt.memberx@sagebase.org

  MemberYAccount:
    Type: OC::ORG::Account
    Properties:
      Alias: org-sagebase-testitorgmgnt-membery
      AccountName: org-sagebase-testitorgmgnt-membery
      RootEmail: aws.testitorgmgnt.membery@sagebase.org
      Tags:
        <<: !Include ./_default_org_tags.yaml
        budget-alarm-threshold: '40'
        account-owner-email: aws.testitorgmgnt.membery@sagebase.org
